#!/usr/bin/env python3
"""
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

def fibonacci_numbers():
    result = 1
    first, second = 1, 2
    flag = True
    # for i in range(10):
    #     print(first)
    while flag:
        print([second, result])
        if second > 4000000:
            print(result)
            return  result
        first, second = second, first + second
        result += second
        # result += second


print(fibonacci_numbers())
